name: sample tag

on: 
  release:
    types: [prereleased, released]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: build ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    timeout-minutes: 180
    strategy:
      matrix:
        targetPlatform:
          - Android
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-Android
      - uses: snow-eigo/unity-builder@fix/getTagVersionBuild
        id: unityBuldStep
        with:
          versioning: Tag
          androidAppBundle: true
          targetPlatform: ${{ matrix.targetPlatform }}
      - run: echo 'Project Version: ${{ steps.unityBuldStep.outputs.buildVersion }}'
      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          retention-days: 1
